// All 290 Kenyan constituencies (IEBC 2013 boundaries), grouped by the 47
// counties in county-code order. Generated identically into both repos.
const CONSTITUENCIES_BY_COUNTY = [
  { county: "Mombasa County", options: ["Changamwe", "Jomvu", "Kisauni", "Nyali", "Likoni", "Mvita"] },
  { county: "Kwale County", options: ["Msambweni", "Lunga Lunga", "Matuga", "Kinango"] },
  { county: "Kilifi County", options: ["Kilifi North", "Kilifi South", "Kaloleni", "Rabai", "Ganze", "Malindi", "Magarini"] },
  { county: "Tana River County", options: ["Garsen", "Galole", "Bura"] },
  { county: "Lamu County", options: ["Lamu East", "Lamu West"] },
  { county: "Taita Taveta County", options: ["Taveta", "Wundanyi", "Mwatate", "Voi"] },
  { county: "Garissa County", options: ["Garissa Township", "Balambala", "Lagdera", "Dadaab", "Fafi", "Ijara"] },
  { county: "Wajir County", options: ["Wajir North", "Wajir East", "Tarbaj", "Wajir West", "Eldas", "Wajir South"] },
  { county: "Mandera County", options: ["Mandera West", "Banissa", "Mandera North", "Mandera South", "Mandera East", "Lafey"] },
  { county: "Marsabit County", options: ["Moyale", "North Horr", "Saku", "Laisamis"] },
  { county: "Isiolo County", options: ["Isiolo North", "Isiolo South"] },
  { county: "Meru County", options: ["Igembe South", "Igembe Central", "Igembe North", "Tigania West", "Tigania East", "North Imenti", "Buuri", "Central Imenti", "South Imenti"] },
  { county: "Tharaka-Nithi County", options: ["Maara", "Chuka/Igambang'ombe", "Tharaka"] },
  { county: "Embu County", options: ["Manyatta", "Runyenjes", "Mbeere South", "Mbeere North"] },
  { county: "Kitui County", options: ["Mwingi North", "Mwingi West", "Mwingi Central", "Kitui West", "Kitui Rural", "Kitui Central", "Kitui East", "Kitui South"] },
  { county: "Machakos County", options: ["Masinga", "Yatta", "Kangundo", "Matungulu", "Kathiani", "Mavoko", "Machakos Town", "Mwala"] },
  { county: "Makueni County", options: ["Mbooni", "Kilome", "Kaiti", "Makueni", "Kibwezi West", "Kibwezi East"] },
  { county: "Nyandarua County", options: ["Kinangop", "Kipipiri", "Ol Kalou", "Ol Jorok", "Ndaragwa"] },
  { county: "Nyeri County", options: ["Tetu", "Kieni", "Mathira", "Othaya", "Mukurweini", "Nyeri Town"] },
  { county: "Kirinyaga County", options: ["Mwea", "Gichugu", "Ndia", "Kirinyaga Central"] },
  { county: "Murang'a County", options: ["Kangema", "Mathioya", "Kiharu", "Kigumo", "Maragwa", "Kandara", "Gatanga"] },
  { county: "Kiambu County", options: ["Gatundu South", "Gatundu North", "Juja", "Thika Town", "Ruiru", "Githunguri", "Kiambu", "Kiambaa", "Kabete", "Kikuyu", "Limuru", "Lari"] },
  { county: "Turkana County", options: ["Turkana North", "Turkana West", "Turkana Central", "Loima", "Turkana South", "Turkana East"] },
  { county: "West Pokot County", options: ["Kapenguria", "Sigor", "Kacheliba", "Pokot South"] },
  { county: "Samburu County", options: ["Samburu West", "Samburu North", "Samburu East"] },
  { county: "Trans Nzoia County", options: ["Kwanza", "Endebess", "Saboti", "Kiminini", "Cherangany"] },
  { county: "Uasin Gishu County", options: ["Soy", "Turbo", "Moiben", "Ainabkoi", "Kapseret", "Kesses"] },
  { county: "Elgeyo-Marakwet County", options: ["Marakwet East", "Marakwet West", "Keiyo North", "Keiyo South"] },
  { county: "Nandi County", options: ["Tinderet", "Aldai", "Nandi Hills", "Chesumei", "Emgwen", "Mosop"] },
  { county: "Baringo County", options: ["Tiaty", "Baringo North", "Baringo Central", "Baringo South", "Mogotio", "Eldama Ravine"] },
  { county: "Laikipia County", options: ["Laikipia West", "Laikipia East", "Laikipia North"] },
  { county: "Nakuru County", options: ["Molo", "Njoro", "Naivasha", "Gilgil", "Kuresoi South", "Kuresoi North", "Subukia", "Rongai", "Bahati", "Nakuru Town West", "Nakuru Town East"] },
  { county: "Narok County", options: ["Kilgoris", "Emurua Dikirr", "Narok North", "Narok East", "Narok South", "Narok West"] },
  { county: "Kajiado County", options: ["Kajiado North", "Kajiado Central", "Kajiado East", "Kajiado West", "Kajiado South"] },
  { county: "Kericho County", options: ["Kipkelion East", "Kipkelion West", "Ainamoi", "Bureti", "Belgut", "Sigowet/Soin"] },
  { county: "Bomet County", options: ["Sotik", "Chepalungu", "Bomet East", "Bomet Central", "Konoin"] },
  { county: "Kakamega County", options: ["Lugari", "Likuyani", "Malava", "Lurambi", "Navakholo", "Mumias West", "Mumias East", "Matungu", "Butere", "Khwisero", "Shinyalu", "Ikolomani"] },
  { county: "Vihiga County", options: ["Vihiga", "Sabatia", "Hamisi", "Luanda", "Emuhaya"] },
  { county: "Bungoma County", options: ["Mt. Elgon", "Sirisia", "Kabuchai", "Bumula", "Kanduyi", "Webuye East", "Webuye West", "Kimilili", "Tongaren"] },
  { county: "Busia County", options: ["Teso North", "Teso South", "Nambale", "Matayos", "Butula", "Funyula", "Budalangi"] },
  { county: "Siaya County", options: ["Ugenya", "Ugunja", "Alego Usonga", "Gem", "Bondo", "Rarieda"] },
  { county: "Kisumu County", options: ["Kisumu East", "Kisumu West", "Kisumu Central", "Seme", "Nyando", "Muhoroni", "Nyakach"] },
  { county: "Homa Bay County", options: ["Kasipul", "Kabondo Kasipul", "Karachuonyo", "Rangwe", "Homa Bay Town", "Ndhiwa", "Suba North", "Suba South"] },
  { county: "Migori County", options: ["Rongo", "Awendo", "Suna East", "Suna West", "Uriri", "Nyatike", "Kuria West", "Kuria East"] },
  { county: "Kisii County", options: ["Bonchari", "South Mugirango", "Bomachoge Borabu", "Bobasi", "Bomachoge Chache", "Nyaribari Masaba", "Nyaribari Chache", "Kitutu Chache North", "Kitutu Chache South"] },
  { county: "Nyamira County", options: ["Kitutu Masaba", "West Mugirango", "North Mugirango", "Borabu"] },
  { county: "Nairobi County", options: ["Westlands", "Dagoretti North", "Dagoretti South", "Lang'ata", "Kibra", "Roysambu", "Kasarani", "Ruaraka", "Embakasi South", "Embakasi North", "Embakasi Central", "Embakasi East", "Embakasi West", "Makadara", "Kamukunji", "Starehe", "Mathare"] },
];

module.exports = { CONSTITUENCIES_BY_COUNTY };
